clear;clc;
load('./../feaSet/Step2_1_b_7_vsmBW_TestQuery_nonSyn.txt');
Step2_1_b_7_vsmBW_TestQuery_nonSyn = sparse(Step2_1_b_7_vsmBW_TestQuery_nonSyn);
load('./../feaSet/Step2_1_b_7_vsmBW_TestTitle_nonSyn.txt');
Step2_1_b_7_vsmBW_TestTitle_nonSyn = sparse(Step2_1_b_7_vsmBW_TestTitle_nonSyn);
load('./../feaSet/Step2_1_b_7_vsmBW_TrainQuery_nonSyn.txt');
Step2_1_b_7_vsmBW_TrainQuery_nonSyn = sparse(Step2_1_b_7_vsmBW_TrainQuery_nonSyn);
load('./../feaSet/Step2_1_b_7_vsmBW_TrainTitle_nonSyn.txt');
Step2_1_b_7_vsmBW_TrainTitle_nonSyn = sparse(Step2_1_b_7_vsmBW_TrainTitle_nonSyn);
load('./../feaSet/Step2_1_b_7_vsmBW_TestQuery_Syn.txt');
Step2_1_b_7_vsmBW_TestQuery_Syn = sparse(Step2_1_b_7_vsmBW_TestQuery_Syn);
load('./../feaSet/Step2_1_b_7_vsmBW_TestTitle_Syn.txt');
Step2_1_b_7_vsmBW_TestTitle_Syn = sparse(Step2_1_b_7_vsmBW_TestTitle_Syn);
load('./../feaSet/Step2_1_b_7_vsmBW_TrainQuery_Syn.txt');
Step2_1_b_7_vsmBW_TrainQuery_Syn = sparse(Step2_1_b_7_vsmBW_TrainQuery_Syn);
load('./../feaSet/Step2_1_b_7_vsmBW_TrainTitle_Syn.txt');
Step2_1_b_7_vsmBW_TrainTitle_Syn = sparse(Step2_1_b_7_vsmBW_TrainTitle_Syn);
save './../feaSet/Step2_1_b_8_vsmBW_nonSyn' '*_nonSyn';
save './../feaSet/Step2_1_b_8_vsmBW_Syn' '*_Syn';